# Configuration file used by Genja to generate this website
# See https://github.com/wigging/genja for more info about Genja

base_url = "https://gavinw.me/git-notes"
posts_output = "."
site_output = "."
title = "Git Notes"